var scene, camera, renderer, spotLight,pointLight, ambientLight,
    start = false,
    log = 1,
    logNum = 0,
    hp = document.getElementsByClassName('hp')[0],
    dialogDiv = document.getElementsByClassName('dialog')[0],
    dialogCon = document.getElementsByClassName('content')[0],
    dianame = document.getElementsByClassName("name")[0],
    dialogKey = true,
    dialogKey2 = true,
    dialogKey3 = true,
    selectAqua = false,
    selectVill = false,
    selectHS = false,
    listener = new THREE.AudioListener(),
    soundGun = new THREE.Audio(listener),
    bgm = new THREE.Audio(listener),
    // soundHS = new THREE.Audio(listener),
    // voiceKey = true,
    auLoader = new THREE.AudioLoader(),
    gunBtn = document.getElementById("btn"),
    bgmBtn = document.getElementById("bgm"),
    tip = document.getElementById('tips'),
    emissiveKey = {"chicken": false},
    mesh = {},
    // worker = new Worker("./src/js/enemyMove.js"),
    raycaster = new THREE.Raycaster(),
    rayTarget,
    rayMouse = new THREE.Vector2(0,0),
    intersect,
    stageNum = 0,
    loader = new THREE.MMDLoader(),
    renderKey = true,
    camCons = {}, //相机约束
    mmdAnimation = {},
    mmdVpd = {},
    enemy = [],
    enemyPos = [],
    helper = {},
    ikHelper = {},
    isMountain = false,
    physicsHelper = {},
    fullscreenElement,
    treeNum = 10,
    bushNum = 60,
    mapAll,
    eve = -1,
    tipKey = false,
    moveSpeedVal,
    armsDirection = new THREE.Vector3(),
    armsY = 0,
    mountainHigh = 250,//山高
    mapSize = 2000,
    worldSize = 5000,
    mapCuts = 10,//地图平面切割成多少份
    mouPointPosition = [],
    arms,//当前所持武器
    armsArr = [],//武器背包
    moveSpeed = 0.7,//移动速度
    jump = true,
    jumpCamY,
    jumpSpeed = 0,
    jumpAcc = 0,
    peopleHeight = 30,
    people,
    squat = false,
    squatSwitch = true,
    squatKey = false,
    runKey = false,
    squatSpeed = 2,
    mmdModelSpeed = {},
    moveDirection = new THREE.Vector3(),
    mouseLock = false,
    mouseDelta = [],
    keyNum = {},
    eY = new THREE.Vector3(0, 1, 0),
    geoContainer = new THREE.Group(),
    obstacle = [],//障碍物
    controls,
    clock = new THREE.Clock(),
    shoot = false,
    shootKey2 = true,
    armsConstraint,
    pointerControls;

mesh.push = Array.prototype.push;
