var file = {
    mountainTexture: "./src/texture/mountain/mountain.jpg",
    mountainNormalTexture: "./src/texture/mountain/mountain_normal.jpg",
    mountainRoughnessTexture: "./src/texture/mountain/mountain_roughness.jpg",
    mountainEmissiveTexture: "./src/texture/mountain/mountain_emissive.jpg",
    SkullsTexture: "./src/texture/PileOfSkulls_Arnold2kBitmap/PileOfSkulls_basecolor.jpg",
    SkullsNormal: "./src/texture/PileOfSkulls_Arnold2kBitmap/PileOfSkulls_normal.jpg",
    SkullsRoughness: "./src/texture/PileOfSkulls_Arnold2kBitmap/PileOfSkulls_roughness.jpg",
    SkullsEmissive: "./src/texture/PileOfSkulls_Arnold2kBitmap/PileOfSkulls_height.jpg",
    // cliffTexture: "./src/texture/FracturedCliff5_Arnold2kBitmap/FracturedCliff5_basecolor.png",
    // cliffNormal: "./src/texture/FracturedCliff5_Arnold2kBitmap/FracturedCliff5_normal.png",
    // cliffRoughness: "./src/texture/FracturedCliff5_Arnold2kBitmap/FracturedCliff5_roughness.png",
    // cliffEmissive: "./src/texture/FracturedCliff5_Arnold2kBitmap/FracturedCliff5_ambientocclusion.png",
    grassTexture: "./src/texture/grass/TexturesCom_Nature_Moss_1K_albedo.jpg",
    grassNormal: "./src/texture/grass/TexturesCom_Nature_Moss_1K_normal.jpg",
    grassRoughness: "./src/texture/grass/TexturesCom_Nature_Moss_1K_roughness.jpg",
    // magmaEmissive: "./src/texture/magma/TexturesCom_Rock_Lava_1K_albedo.jpg",
    // magmaNormal: "./src/texture/magma/TexturesCom_Rock_Lava_1K_normal.jpg",
    // magmaRoughness: "./src/texture/magma/TexturesCom_Rock_Lava_1K_roughness.jpg",
    // magmaTexture: "./src/texture/magma/TexturesCom_Rock_Lava_1K_emissive.jpg",
    // sandsTexture: "./src/texture/sands/T1exturesCom_MuddySand2_2x2_8K_albedo.jpg",
    // sandsNormal: "./src/texture/sands/T1exturesCom_MuddySand2_2x2_8K_normal.jpg",
    // sandsRoughness: "./src/texture/sands/rough.jpg",
    // sandsEmissive: "./src/texture/sands/emissive.jpg",
    wordTexture1: "./src/texture/SumerianTrim_Arnold2kBitmap/SumerianTrim_basecolor.jpg",
    wordNormal1: "./src/texture/SumerianTrim_Arnold2kBitmap/SumerianTrim_normal.jpg",
    wordRoughness1: "./src/texture/SumerianTrim_Arnold2kBitmap/SumerianTrim_roughness.jpg",
    wordEmissive1: "./src/texture/SumerianTrim_Arnold2kBitmap/SumerianTrim_emissive.jpg",
    skyTexture1: "./src/texture/skybox/TG701_outright.png",
    skyTexture2: "./src/texture/skybox/TG701_outleft.png",
    skyTexture3: "./src/texture/skybox/TG701_outback.png",
    skyTexture4: "./src/texture/skybox/TG701_outfront.png",
    skyTexture5: "./src/texture/skybox/TG701_outtop.png",
    skyTexture6: "./src/texture/skybox/TG701_outbottom.png",
    sky2Texture1: "./src/texture/skybox/TG201_outright.png",
    sky2Texture2: "./src/texture/skybox/TG201_outleft.png",
    sky2Texture3: "./src/texture/skybox/TG201_outback.png",
    sky2Texture4: "./src/texture/skybox/TG201_outfront.png",
    sky2Texture5: "./src/texture/skybox/TG201_outtop.png",
    sky2Texture6: "./src/texture/skybox/TG201_outbottom.png",
    desertEagle: "./src/model/desert_eagle/deagle.obj",
    desertEagleMtl: "./src/model/desert_eagle/deagle.mtl",
    // sword: "./src/model/sword/sword.obj",
    // swordMtl: "./src/model/sword/sword.mtl",
    // m4a1: "./src/model/m4a1_s/obj/m4a1_s.obj",
    font: "./src/font/FangSong_Regular.json",
    bigTree: "./src/model/tree/big_tree.obj",
    bigTreeMtl: "./src/model/tree/big_tree.mtl",
    treeLeaf: "./src/model/tree/tree_leaf.obj",
    treeLeafMtl: "./src/model/tree/tree_leaf.mtl",
    treeNoLeaf: "./src/model/tree/tree_noleaf.obj",
    treeNoLeafMtl: "./src/model/tree/tree_nolear.mtl",
    bush: "./src/model/Bush/Bush1.obj",
    bushMtl: "./src/model/Bush/Bush1.mtl",
    enemy: "./src/model/enemy/enemy.obj",
    doorTexture: "./src/texture/BrokenLimestoneBrickPath_Arnold2kBitmap/BrokenLimestoneBrickPath_basecolor.jpg",
    doorNormal: "./src/texture/BrokenLimestoneBrickPath_Arnold2kBitmap/BrokenLimestoneBrickPath_normal.jpg",
    doorRoughness: "./src/texture/BrokenLimestoneBrickPath_Arnold2kBitmap/BrokenLimestoneBrickPath_roughness.jpg",
    doorEmissive: "./src/texture/BrokenLimestoneBrickPath_Arnold2kBitmap/BrokenLimestoneBrickPath_height.jpg",
    wastelandTexture: "./src/texture/GnarlyRootWet_Arnold2kBitmap/GnarlyRootWet_basecolor.jpg",
    wastelandNormal: "./src/texture/GnarlyRootWet_Arnold2kBitmap/GnarlyRootWet_normal.jpg",
    wastelandRoughness: "./src/texture/GnarlyRootWet_Arnold2kBitmap/GnarlyRootWet_roughness.jpg",
    wastelandEmissive: "./src/texture/GnarlyRootWet_Arnold2kBitmap/GnarlyRootWet_height.jpg",
    house1: "./src/model/house1/GosTHouse/3D models/Gost House (5).obj",
    house1Mtl: "./src/model/house1/GosTHouse/3D models/Gost House (4).mtl",
    house2: "./src/model/house2/house.obj",
    house2Mtl: "./src/model/house2/house.mtl",
    chicken: "./src/model/chicken/chicken.obj",
    chickenMtl: "./src/model/chicken/chicken.mtl",
    stickMan: "./src/model/stickman/stickman.pmx",
    villageA: "./src/vmd/villagerA.vmd",
    villageB: "./src/vmd/villagerB.vmd",
    villageC: "./src/vmd/villagerC.vmd",
    villageD: "./src/vmd/villagerD.vmd",
    villageD2: "./src/vmd/villagerD2.vmd",
    villageE: "./src/vmd/villagerE.vmd",
    // villagerA1: "./src/vpd/villagerA2.vpd",
    aqua :{
        model: "./src/model/mmdmodel/aqua/aqua/aqua101.pmx",
        vmd: {
            walk: "./src/vmd/girl_walk.vmd",
            stand: "./src/vmd/aqua_stand.vmd",
        },
        voice: "",
    },
    wanghasang: {
        model: "./src/model/mmdmodel/hasang/hasang/data/hasang.pmx",
        vmd: {
            stand: "./src/vmd/hasang.vmd"
        },
        voice: "",
    }
}